# Generated by Django 5.1.1 on 2024-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('below Php 9,000', 'below Php 9,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('above Php 35,000', 'above Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Judaism', 'Judaism'), ('Islam', 'Islam'), ('Buddhism', 'Buddhism'), ('Roman catholic', 'Roman Catholic'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Sikhism', 'Sikhism'), ('Other', 'Other')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Enrolled', 'Currently Enrolled'), ('For Graduation', 'For Graduation'), ('For Promotion', 'For Promotion'), ('For Dropout', 'For Dropout'), ('For Retention', 'For Retention'), ('For Transfer', 'For Transfer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('IA', 'IA'), ('ICT', 'ICT'), ('GAS', 'GAS'), ('HESS', 'HESS'), ('HE', 'HE'), ('BAM', 'BAM'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('TVL', 'TVL'), ('STEM', 'STEM'), ('Not Applicable (JHS)', 'Not Applicable (JHS)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Moved In', 'Moved In'), ('Transferred In', 'Transferred In')], default='Regular', max_length=15, null=True),
        ),
    ]
