# Generated by Django 5.1.1 on 2024-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('above Php 35,000', 'above Php 35,000'), ('below Php 9,000', 'below Php 9,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism'), ('Islam', 'Islam'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Roman catholic', 'Roman Catholic'), ('Other', 'Other'), ('Christianity', 'Christianity')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly'), ('1st Semester', '1st Semester')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Enrolled', 'Currently Enrolled'), ('For Promotion', 'For Promotion'), ('For Transfer', 'For Transfer'), ('For Graduation', 'For Graduation'), ('For Dropout', 'For Dropout'), ('For Retention', 'For Retention')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('STEM', 'STEM'), ('GAS', 'GAS'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('HE', 'HE'), ('BAM', 'BAM'), ('ICT', 'ICT'), ('HESS', 'HESS'), ('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('IA', 'IA'), ('TVL', 'TVL')], max_length=50, null=True),
        ),
    ]
