# Generated by Django 5.1.1 on 2024-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LRN',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('above Php 35,000', 'above Php 35,000'), ('below Php 9,000', 'below Php 9,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Christianity', 'Christianity'), ('Roman catholic', 'Roman Catholic'), ('Sikhism', 'Sikhism'), ('Hinduism', 'Hinduism'), ('Islam', 'Islam'), ('Other', 'Other'), ('Buddhism', 'Buddhism'), ('Judaism', 'Judaism')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Promotion', 'For Promotion'), ('For Transfer', 'For Transfer'), ('For Retention', 'For Retention'), ('Currently Enrolled', 'Currently Enrolled'), ('For Graduation', 'For Graduation'), ('For Dropout', 'For Dropout')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('SPORTS & ARTS', 'SPORTS & ARTS'), ('ICT', 'ICT'), ('TVL', 'TVL'), ('STEM', 'STEM'), ('GAS', 'GAS'), ('BAM', 'BAM'), ('HE', 'HE'), ('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('HESS', 'HESS'), ('IA', 'IA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Transferred In', 'Transferred In'), ('Moved In', 'Moved In'), ('Regular', 'Regular')], default='Regular', max_length=15, null=True),
        ),
    ]
