# Generated by Django 5.1.1 on 2024-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_household_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('below Php 9,000', 'below Php 9,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('above Php 35,000', 'above Php 35,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Roman catholic', 'Roman Catholic'), ('Buddhism', 'Buddhism'), ('Sikhism', 'Sikhism'), ('Christianity', 'Christianity'), ('Other', 'Other'), ('Hinduism', 'Hinduism'), ('Judaism', 'Judaism'), ('Islam', 'Islam')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Graduation', 'For Graduation'), ('For Dropout', 'For Dropout'), ('Currently Enrolled', 'Currently Enrolled'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Transfer', 'For Transfer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('SPORTS & ARTS', 'SPORTS & ARTS'), ('IA', 'IA'), ('TVL', 'TVL'), ('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('STEM', 'STEM'), ('GAS', 'GAS'), ('HE', 'HE'), ('BAM', 'BAM'), ('HESS', 'HESS'), ('ICT', 'ICT')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Transferred In', 'Transferred In'), ('Regular', 'Regular'), ('Moved In', 'Moved In')], default='Regular', max_length=15, null=True),
        ),
    ]
