# Generated by Django 5.1.1 on 2024-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_household_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('below Php 9,000', 'below Php 9,000'), ('above Php 35,000', 'above Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Roman catholic', 'Roman Catholic'), ('Christianity', 'Christianity'), ('Other', 'Other'), ('Islam', 'Islam'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism'), ('Hinduism', 'Hinduism'), ('Buddhism', 'Buddhism')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly'), ('1st Semester', '1st Semester')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Promotion', 'For Promotion'), ('Currently Enrolled', 'Currently Enrolled'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation'), ('For Transfer', 'For Transfer'), ('For Dropout', 'For Dropout')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('HE', 'HE'), ('BAM', 'BAM'), ('STEM', 'STEM'), ('GAS', 'GAS'), ('IA', 'IA'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('ICT', 'ICT'), ('HESS', 'HESS'), ('TVL', 'TVL'), ('Not Applicable (JHS)', 'Not Applicable (JHS)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Transferred In', 'Transferred In'), ('Moved In', 'Moved In')], default='Regular', max_length=15, null=True),
        ),
    ]
