# Generated by Django 5.1.1 on 2024-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_classroom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('above Php 35,000', 'above Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('below Php 9,000', 'below Php 9,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_dropout',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_returnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_working_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Sikhism', 'Sikhism'), ('Roman catholic', 'Roman Catholic'), ('Christianity', 'Christianity'), ('Other', 'Other'), ('Judaism', 'Judaism'), ('Islam', 'Islam'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly'), ('1st Semester', '1st Semester')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Retention', 'For Retention'), ('For Transfer', 'For Transfer'), ('For Dropout', 'For Dropout'), ('For Promotion', 'For Promotion'), ('Currently Enrolled', 'Currently Enrolled'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('GAS', 'GAS'), ('HE', 'HE'), ('IA', 'IA'), ('ICT', 'ICT'), ('STEM', 'STEM'), ('BAM', 'BAM'), ('HESS', 'HESS'), ('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('TVL', 'TVL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Moved In', 'Moved In'), ('Transferred In', 'Transferred In')], default='Regular', max_length=15, null=True),
        ),
    ]
