# Generated by Django 5.1.1 on 2024-10-28 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_household_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('below Php 9,000', 'below Php 9,000'), ('above Php 35,000', 'above Php 35,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Sikhism', 'Sikhism'), ('Buddhism', 'Buddhism'), ('Hinduism', 'Hinduism'), ('Other', 'Other'), ('Islam', 'Islam'), ('Judaism', 'Judaism'), ('Roman catholic', 'Roman Catholic'), ('Christianity', 'Christianity')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('Yearly', 'Yearly'), ('2nd Semester', '2nd Semester')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Transfer', 'For Transfer'), ('For Dropout', 'For Dropout'), ('Currently Enrolled', 'Currently Enrolled'), ('For Promotion', 'For Promotion'), ('For Retention', 'For Retention'), ('For Graduation', 'For Graduation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('GAS', 'GAS'), ('HESS', 'HESS'), ('TVL', 'TVL'), ('ICT', 'ICT'), ('HE', 'HE'), ('STEM', 'STEM'), ('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('IA', 'IA'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('BAM', 'BAM')], max_length=50, null=True),
        ),
    ]
