# Generated by Django 5.1.1 on 2024-10-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_household_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('above Php 35,000', 'above Php 35,000'), ('below Php 9,000', 'below Php 9,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Roman catholic', 'Roman Catholic'), ('Other', 'Other'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Sikhism', 'Sikhism'), ('Judaism', 'Judaism'), ('Buddhism', 'Buddhism')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('1st Semester', '1st Semester'), ('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Promotion', 'For Promotion'), ('For Graduation', 'For Graduation'), ('For Retention', 'For Retention'), ('For Transfer', 'For Transfer'), ('Currently Enrolled', 'Currently Enrolled'), ('For Dropout', 'For Dropout')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('IA', 'IA'), ('ICT', 'ICT'), ('HE', 'HE'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('BAM', 'BAM'), ('GAS', 'GAS'), ('HESS', 'HESS'), ('STEM', 'STEM'), ('TVL', 'TVL')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Transferred In', 'Transferred In'), ('Moved In', 'Moved In')], default='Regular', max_length=15, null=True),
        ),
    ]
