# Generated by Django 5.1.1 on 2024-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_household_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='LRN',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('above Php 35,000', 'above Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('below Php 9,000', 'below Php 9,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Buddhism', 'Buddhism'), ('Christianity', 'Christianity'), ('Other', 'Other'), ('Roman catholic', 'Roman Catholic'), ('Hinduism', 'Hinduism'), ('Judaism', 'Judaism'), ('Sikhism', 'Sikhism')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('2nd Semester', '2nd Semester'), ('1st Semester', '1st Semester'), ('Yearly', 'Yearly')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Graduation', 'For Graduation'), ('For Retention', 'For Retention'), ('For Transfer', 'For Transfer'), ('For Dropout', 'For Dropout'), ('Currently Enrolled', 'Currently Enrolled'), ('For Promotion', 'For Promotion')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('BAM', 'BAM'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('HESS', 'HESS'), ('ICT', 'ICT'), ('IA', 'IA'), ('TVL', 'TVL'), ('STEM', 'STEM'), ('HE', 'HE'), ('GAS', 'GAS')], max_length=50, null=True),
        ),
    ]
