# Generated by Django 5.1.1 on 2024-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_lrn_alter_student_household_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('below Php 9,000', 'below Php 9,000'), ('above Php 35,000', 'above Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000'), ('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Other', 'Other'), ('Buddhism', 'Buddhism'), ('Judaism', 'Judaism'), ('Christianity', 'Christianity'), ('Hinduism', 'Hinduism'), ('Sikhism', 'Sikhism'), ('Roman catholic', 'Roman Catholic')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('2nd Semester', '2nd Semester'), ('Yearly', 'Yearly'), ('1st Semester', '1st Semester')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('Currently Enrolled', 'Currently Enrolled'), ('For Retention', 'For Retention'), ('For Promotion', 'For Promotion'), ('For Graduation', 'For Graduation'), ('For Transfer', 'For Transfer'), ('For Dropout', 'For Dropout')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('HESS', 'HESS'), ('ICT', 'ICT'), ('TVL', 'TVL'), ('STEM', 'STEM'), ('BAM', 'BAM'), ('IA', 'IA'), ('HE', 'HE'), ('GAS', 'GAS'), ('SPORTS & ARTS', 'SPORTS & ARTS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Moved In', 'Moved In'), ('Transferred In', 'Transferred In')], default='Regular', max_length=15, null=True),
        ),
    ]
