# Generated by Django 5.1.1 on 2024-11-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_student_household_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='household_income',
            field=models.CharField(blank=True, choices=[('from Php 18,000 - Php 35,000', 'from Php 18,000 - Php 35,000'), ('below Php 9,000', 'below Php 9,000'), ('above Php 35,000', 'above Php 35,000'), ('from Php 9,000 - Php 18,000', 'from Php 9,000 - Php 18,000')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Other', 'Other'), ('Sikhism', 'Sikhism'), ('Buddhism', 'Buddhism'), ('Roman catholic', 'Roman Catholic'), ('Judaism', 'Judaism'), ('Hinduism', 'Hinduism'), ('Christianity', 'Christianity'), ('Islam', 'Islam')], default='other', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(blank=True, choices=[('2nd Semester', '2nd Semester'), ('1st Semester', '1st Semester'), ('Yearly', 'Yearly')], default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('For Graduation', 'For Graduation'), ('For Retention', 'For Retention'), ('Currently Enrolled', 'Currently Enrolled'), ('For Dropout', 'For Dropout'), ('For Promotion', 'For Promotion'), ('For Transfer', 'For Transfer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='strand',
            field=models.CharField(blank=True, choices=[('BAM', 'BAM'), ('TVL', 'TVL'), ('GAS', 'GAS'), ('STEM', 'STEM'), ('IA', 'IA'), ('HE', 'HE'), ('SPORTS & ARTS', 'SPORTS & ARTS'), ('Not Applicable (JHS)', 'Not Applicable (JHS)'), ('ICT', 'ICT'), ('HESS', 'HESS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_status',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Transferred In', 'Transferred In'), ('Moved In', 'Moved In')], default='Regular', max_length=15, null=True),
        ),
    ]
