# Generated by Django 5.1.1 on 2024-10-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradelevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Transitioning', 'Transitioning'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 11', 'Grade 11'), ('Grade 12', 'Grade 12'), ('Grade 10', 'Grade 10'), ('Grade 9', 'Grade 9')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.CharField(default=None, max_length=50, null=True)),
                ('teacher', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.teacher', verbose_name='Teachers')),
                ('gradelevel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='classrooms.gradelevel')),
            ],
            options={
                'verbose_name_plural': 'Classrooms',
            },
        ),
    ]
