# Generated by Django 5.1.1 on 2024-10-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classrooms', '0003_alter_gradelevel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradelevel',
            name='grade',
            field=models.CharField(choices=[('Grade 10', 'Grade 10'), ('Grade 8', 'Grade 8'), ('Grade 11', 'Grade 11'), ('Transitioning', 'Transitioning'), ('Grade 12', 'Grade 12'), ('Grade 7', 'Grade 7'), ('Grade 9', 'Grade 9')], max_length=20, unique=True),
        ),
    ]
