# Generated by Django 5.1.1 on 2024-10-23 14:32

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('appt_date', models.DateField(blank=True, null=True)),
                ('special_assignment', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('employee_id', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('rank', models.CharField(choices=[('Teacher II', 'Teacher II'), ('Master Teacher IV', 'Master Teacher IV'), ('Master Teacher I', 'Master Teacher I'), ('Teacher VI', 'Teacher VI'), ('Master Teacher III', 'Master Teacher III'), ('Teacher I', 'Teacher I'), ('Teacher VII', 'Teacher VII'), ('Master Teacher II', 'Master Teacher II'), ('Teacher IV', 'Teacher IV'), ('Teacher III', 'Teacher III'), ('Teacher V', 'Teacher V')], default='None', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
