# Generated by Django 5.1.1 on 2024-10-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher I', 'Master Teacher I'), ('Teacher II', 'Teacher II'), ('Teacher IV', 'Teacher IV'), ('Teacher III', 'Teacher III'), ('Teacher VII', 'Teacher VII'), ('Master Teacher III', 'Master Teacher III'), ('Teacher VI', 'Teacher VI'), ('Teacher I', 'Teacher I'), ('Teacher V', 'Teacher V'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher IV', 'Master Teacher IV')], default='None', max_length=30),
        ),
    ]
