# Generated by Django 5.1.1 on 2024-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher III', 'Teacher III'), ('Teacher V', 'Teacher V'), ('Master Teacher I', 'Master Teacher I'), ('Teacher IV', 'Teacher IV'), ('Teacher VI', 'Teacher VI'), ('Master Teacher II', 'Master Teacher II'), ('Teacher VII', 'Teacher VII'), ('Teacher II', 'Teacher II'), ('Master Teacher III', 'Master Teacher III'), ('Teacher I', 'Teacher I'), ('Master Teacher IV', 'Master Teacher IV')], default='None', max_length=30),
        ),
    ]
