# Generated by Django 5.1.1 on 2024-10-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher III', 'Master Teacher III'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher I', 'Master Teacher I'), ('Teacher III', 'Teacher III'), ('Teacher VII', 'Teacher VII'), ('Teacher II', 'Teacher II'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher VI', 'Teacher VI'), ('Teacher I', 'Teacher I'), ('Teacher IV', 'Teacher IV'), ('Teacher V', 'Teacher V')], default='None', max_length=30),
        ),
    ]
