# Generated by Django 5.1.1 on 2024-10-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher V', 'Teacher V'), ('Teacher I', 'Teacher I'), ('Teacher VII', 'Teacher VII'), ('Master Teacher II', 'Master Teacher II'), ('Teacher II', 'Teacher II'), ('Teacher III', 'Teacher III'), ('Teacher VI', 'Teacher VI'), ('Master Teacher III', 'Master Teacher III'), ('Teacher IV', 'Teacher IV'), ('Master Teacher IV', 'Master Teacher IV'), ('Master Teacher I', 'Master Teacher I')], default='None', max_length=30),
        ),
    ]
