# Generated by Django 5.1.1 on 2024-10-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher IV', 'Teacher IV'), ('Teacher VII', 'Teacher VII'), ('Teacher II', 'Teacher II'), ('Teacher III', 'Teacher III'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher VI', 'Teacher VI'), ('Teacher I', 'Teacher I'), ('Master Teacher III', 'Master Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('Teacher V', 'Teacher V')], default='None', max_length=30),
        ),
    ]
