# Generated by Django 5.1.1 on 2024-10-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher II', 'Master Teacher II'), ('Teacher III', 'Teacher III'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher IV', 'Teacher IV'), ('Teacher I', 'Teacher I'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher III', 'Master Teacher III'), ('Teacher VII', 'Teacher VII'), ('Teacher V', 'Teacher V'), ('Teacher VI', 'Teacher VI'), ('Teacher II', 'Teacher II')], default='None', max_length=30),
        ),
    ]
