# Generated by Django 5.1.1 on 2024-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher II', 'Teacher II'), ('Teacher IV', 'Teacher IV'), ('Teacher V', 'Teacher V'), ('Master Teacher I', 'Master Teacher I'), ('Teacher VII', 'Teacher VII'), ('Teacher I', 'Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher III', 'Master Teacher III'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher III', 'Teacher III'), ('Teacher VI', 'Teacher VI')], default='None', max_length=30),
        ),
    ]
