# Generated by Django 5.1.1 on 2024-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher IV', 'Teacher IV'), ('Master Teacher IV', 'Master Teacher IV'), ('Master Teacher II', 'Master Teacher II'), ('Teacher I', 'Teacher I'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher III', 'Master Teacher III'), ('Teacher II', 'Teacher II'), ('Teacher VI', 'Teacher VI'), ('Teacher III', 'Teacher III'), ('Teacher VII', 'Teacher VII'), ('Teacher V', 'Teacher V')], default='None', max_length=30),
        ),
    ]
