# Generated by Django 5.1.1 on 2024-10-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher II', 'Master Teacher II'), ('Teacher V', 'Teacher V'), ('Master Teacher I', 'Master Teacher I'), ('Teacher VI', 'Teacher VI'), ('Teacher VII', 'Teacher VII'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher IV', 'Teacher IV'), ('Teacher II', 'Teacher II'), ('Teacher I', 'Teacher I'), ('Master Teacher III', 'Master Teacher III'), ('Teacher III', 'Teacher III')], default='None', max_length=30),
        ),
    ]
