# Generated by Django 5.1.1 on 2024-10-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher V', 'Teacher V'), ('Teacher II', 'Teacher II'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher VII', 'Teacher VII'), ('Teacher III', 'Teacher III'), ('Teacher I', 'Teacher I'), ('Teacher VI', 'Teacher VI'), ('Master Teacher I', 'Master Teacher I'), ('Teacher IV', 'Teacher IV'), ('Master Teacher III', 'Master Teacher III')], default='None', max_length=30),
        ),
    ]
