# Generated by Django 5.1.1 on 2024-10-25 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_teacher_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher III', 'Master Teacher III'), ('Master Teacher II', 'Master Teacher II'), ('Teacher I', 'Teacher I'), ('Teacher V', 'Teacher V'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher VI', 'Teacher VI'), ('Teacher IV', 'Teacher IV'), ('Teacher III', 'Teacher III'), ('Teacher II', 'Teacher II'), ('Teacher VII', 'Teacher VII')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
