# Generated by Django 5.1.1 on 2024-10-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_teacher_rank_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher II', 'Teacher II'), ('Teacher V', 'Teacher V'), ('Master Teacher I', 'Master Teacher I'), ('Teacher VI', 'Teacher VI'), ('Teacher III', 'Teacher III'), ('Teacher IV', 'Teacher IV'), ('Master Teacher III', 'Master Teacher III'), ('Teacher VII', 'Teacher VII'), ('Teacher I', 'Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher IV', 'Master Teacher IV')], default='None', max_length=30),
        ),
    ]
