# Generated by Django 5.1.1 on 2024-10-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher IV', 'Teacher IV'), ('Teacher V', 'Teacher V'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher VI', 'Teacher VI'), ('Teacher II', 'Teacher II'), ('Master Teacher II', 'Master Teacher II'), ('Teacher I', 'Teacher I'), ('Teacher VII', 'Teacher VII'), ('Teacher III', 'Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher III', 'Master Teacher III')], default='None', max_length=30),
        ),
    ]
