# Generated by Django 5.1.1 on 2024-10-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher IV', 'Master Teacher IV'), ('Teacher III', 'Teacher III'), ('Teacher II', 'Teacher II'), ('Teacher VII', 'Teacher VII'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher III', 'Master Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Teacher VI', 'Teacher VI'), ('Teacher IV', 'Teacher IV'), ('Teacher V', 'Teacher V'), ('Teacher I', 'Teacher I')], default='None', max_length=30),
        ),
    ]
