# Generated by Django 5.1.1 on 2024-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher VI', 'Teacher VI'), ('Master Teacher III', 'Master Teacher III'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher VII', 'Teacher VII'), ('Master Teacher I', 'Master Teacher I'), ('Teacher III', 'Teacher III'), ('Teacher V', 'Teacher V'), ('Teacher II', 'Teacher II'), ('Teacher I', 'Teacher I'), ('Master Teacher II', 'Master Teacher II'), ('Teacher IV', 'Teacher IV')], default='None', max_length=30),
        ),
    ]
