# Generated by Django 5.1.1 on 2024-10-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher II', 'Master Teacher II'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher VII', 'Teacher VII'), ('Teacher VI', 'Teacher VI'), ('Teacher I', 'Teacher I'), ('Teacher V', 'Teacher V'), ('Teacher III', 'Teacher III'), ('Master Teacher I', 'Master Teacher I'), ('Teacher II', 'Teacher II'), ('Teacher IV', 'Teacher IV'), ('Master Teacher III', 'Master Teacher III')], default='None', max_length=30),
        ),
    ]
