# Generated by Django 5.1.1 on 2024-11-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Master Teacher III', 'Master Teacher III'), ('Teacher VI', 'Teacher VI'), ('Teacher II', 'Teacher II'), ('Teacher III', 'Teacher III'), ('Teacher VII', 'Teacher VII'), ('Teacher IV', 'Teacher IV'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher V', 'Teacher V'), ('Master Teacher I', 'Master Teacher I'), ('Teacher I', 'Teacher I'), ('Master Teacher II', 'Master Teacher II')], default='None', max_length=30),
        ),
    ]
