# Generated by Django 5.1.1 on 2024-10-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher VII', 'Teacher VII'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher I', 'Master Teacher I'), ('Master Teacher III', 'Master Teacher III'), ('Master Teacher IV', 'Master Teacher IV'), ('Teacher IV', 'Teacher IV'), ('Teacher V', 'Teacher V'), ('Teacher II', 'Teacher II'), ('Teacher I', 'Teacher I'), ('Teacher III', 'Teacher III'), ('Teacher VI', 'Teacher VI')], default='None', max_length=30),
        ),
    ]
