# Generated by Django 5.1.1 on 2024-10-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_alter_teacher_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='rank',
            field=models.CharField(choices=[('Teacher I', 'Teacher I'), ('Teacher V', 'Teacher V'), ('Teacher III', 'Teacher III'), ('Master Teacher II', 'Master Teacher II'), ('Master Teacher I', 'Master Teacher I'), ('Teacher VII', 'Teacher VII'), ('Teacher VI', 'Teacher VI'), ('Teacher IV', 'Teacher IV'), ('Master Teacher III', 'Master Teacher III'), ('Teacher II', 'Teacher II'), ('Master Teacher IV', 'Master Teacher IV')], default='None', max_length=30),
        ),
    ]
